# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/04_inference.cyclegan.ipynb (unless otherwise specified).

__all__ = ['FolderDataset', 'load_dataset', 'get_preds_cyclegan']

# Cell
from ..models.cyclegan import *
from ..train.cyclegan import *
from ..data.unpaired import *
from fastai.vision.all import *
import torch
from torch.utils.data import Dataset, DataLoader
import torchvision
import glob
from fastprogress.fastprogress import progress_bar
import os
import PIL

# Cell
class FolderDataset(Dataset):
    """
    A PyTorch Dataset class that can be created from a folder `path` of images, for the sole purpose of inference. Optional `transforms`
    can be provided.

    Attributes: \n
    `self.files`: A list of the filenames in the folder. \n
    `self.totensor`: `torchvision.transforms.ToTensor` transform. \n
    `self.transform`: The transforms passed in as `transforms` to the constructor.
    """
    def __init__(self, path,transforms=None):
        """Constructor for this PyTorch Dataset, need to pass the `path`"""
        self.files = glob.glob(path+'/*')
        self.totensor = torchvision.transforms.ToTensor()
        if transforms:
            self.transform = torchvision.transforms.Compose(transforms)
        else:
            self.transform = lambda x: x

    def __len__(self):
        return len(self.files)

    def __getitem__(self, idx):
        image = PIL.Image.open(self.files[idx % len(self.files)])
        image = self.totensor(image)
        image = self.transform(image)
        return self.files[idx], image

# Cell
def load_dataset(test_path,bs=4,num_workers=4):
    "A helper function for getting a DataLoader for images in the folder `test_path`, with batch size `bs`, and number of workers `num_workers`"
    dataset = FolderDataset(
            path=test_path,
            transforms=[torchvision.transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))]
        )
    loader = torch.utils.data.DataLoader(
            dataset,
            batch_size=bs,
            num_workers=num_workers,
            shuffle=True
        )
    return loader

# Cell
def get_preds_cyclegan(learn,test_path,pred_path,bs=4,num_workers=4,suffix='tif'):
    """
    A prediction function that takes the Learner object `learn` with the trained model, the `test_path` folder with the images to perform
    batch inference on, and the output folder `pred_path` where the predictions will be saved, with a batch size `bs`, `num_workers`,
    and suffix of the prediction images `suffix` (default='png').
    """

    assert os.path.exists(test_path)

    if not os.path.exists(pred_path):
        os.mkdir(pred_path)

    test_dl = load_dataset(test_path,bs,num_workers)
    model = learn.model.G_B.cuda()
    for i, xb in progress_bar(enumerate(test_dl),total=len(test_dl)):
        fn, im = xb
        preds = (model(im.cuda())/2 + 0.5)
        for i in range(len(fn)):
            new_fn = os.path.join(pred_path,'.'.join([os.path.basename(fn[i]).split('.')[0]+'_fakeB',suffix]))
            torchvision.utils.save_image(preds[i],new_fn)