# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"convT_norm_relu": "01_models_cyclegan.ipynb",
         "pad_conv_norm_relu": "01_models_cyclegan.ipynb",
         "ResnetBlock": "01b_models_junyanz.ipynb",
         "resnet_generator": "01_models_cyclegan.ipynb",
         "compare_networks": "01_models_cyclegan.ipynb",
         "conv_norm_lr": "01_models_cyclegan.ipynb",
         "discriminator": "01_models_cyclegan.ipynb",
         "CycleGAN": "01_models_cyclegan.ipynb",
         "Identity": "01b_models_junyanz.ipynb",
         "get_norm_layer": "01b_models_junyanz.ipynb",
         "get_scheduler": "01b_models_junyanz.ipynb",
         "init_weights": "01b_models_junyanz.ipynb",
         "init_net": "01b_models_junyanz.ipynb",
         "define_G": "01b_models_junyanz.ipynb",
         "define_D": "01b_models_junyanz.ipynb",
         "GANLoss": "01b_models_junyanz.ipynb",
         "cal_gradient_penalty": "01b_models_junyanz.ipynb",
         "ResnetGenerator": "01b_models_junyanz.ipynb",
         "UnetGenerator": "01b_models_junyanz.ipynb",
         "UnetSkipConnectionBlock": "01b_models_junyanz.ipynb",
         "NLayerDiscriminator": "01b_models_junyanz.ipynb",
         "PixelDiscriminator": "01b_models_junyanz.ipynb"}

modules = ["models.py",
           "models_junyanz.py"]

doc_url = "https://tmabraham.github.io/UPIT"

git_url = "https://github.com/tmabraham/UPIT/tree/master/"

def custom_doc_links(name): return None
