# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"convT_norm_relu": "01_models.cyclegan.ipynb",
         "pad_conv_norm_relu": "01_models.cyclegan.ipynb",
         "ResnetBlock": "01b_models.junyanz.ipynb",
         "resnet_generator": "01_models.cyclegan.ipynb",
         "compare_networks": "01_models.cyclegan.ipynb",
         "conv_norm_lr": "01_models.cyclegan.ipynb",
         "discriminator": "01_models.cyclegan.ipynb",
         "CycleGAN": "01_models.cyclegan.ipynb",
         "Identity": "01b_models.junyanz.ipynb",
         "get_norm_layer": "01b_models.junyanz.ipynb",
         "get_scheduler": "01b_models.junyanz.ipynb",
         "init_weights": "01b_models.junyanz.ipynb",
         "init_net": "01b_models.junyanz.ipynb",
         "define_G": "01b_models.junyanz.ipynb",
         "define_D": "01b_models.junyanz.ipynb",
         "GANLoss": "01b_models.junyanz.ipynb",
         "cal_gradient_penalty": "01b_models.junyanz.ipynb",
         "ResnetGenerator": "01b_models.junyanz.ipynb",
         "UnetGenerator": "01b_models.junyanz.ipynb",
         "UnetSkipConnectionBlock": "01b_models.junyanz.ipynb",
         "NLayerDiscriminator": "01b_models.junyanz.ipynb",
         "PixelDiscriminator": "01b_models.junyanz.ipynb",
         "RandPair": "02_data.unpaired.ipynb",
         "get_dls": "02_data.unpaired.ipynb",
         "CycleGANLoss": "03_train.cyclegan.ipynb",
         "CycleGANTrainer": "03_train.cyclegan.ipynb",
         "ShowCycleGANImgsCallback": "03_train.cyclegan.ipynb",
         "combined_flat_anneal": "03_train.cyclegan.ipynb",
         "Learner.fit_flat_lin": "03_train.cyclegan.ipynb",
         "cycle_learner": "03_train.cyclegan.ipynb",
         "FolderDataset": "04_inference.cyclegan.ipynb",
         "load_dataset": "04_inference.cyclegan.ipynb",
         "get_preds_cyclegan": "04_inference.cyclegan.ipynb",
         "export_generator": "04_inference.cyclegan.ipynb"}

modules = ["models/cyclegan.py",
           "models/junyanz.py",
           "data/unpaired.py",
           "train/cyclegan.py",
           "inference/cyclegan.py",
           "metrics.py"]

doc_url = "https://tmabraham.github.io/UPIT"

git_url = "https://github.com/tmabraham/UPIT/tree/master/"

def custom_doc_links(name): return None
